"""add video path fields to violation

Revision ID: d0c68ef3417f
Revises: 45e1ff286fa3
Create Date: 2025-05-12 16:41:04.352602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c68ef3417f'
down_revision: Union[str, None] = '45e1ff286fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('processed_video_path', sa.String(length=256), nullable=True))
    op.add_column('violations', sa.Column('original_video_path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violations', 'original_video_path')
    op.drop_column('violations', 'processed_video_path')
    # ### end Alembic commands ###
